<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'badge' => '2',
                'badgeClass' => 'badge badge-light-warning rounded-pill ms-auto me-1',
                'url' => NULL,
                'name' => 'Dashboards',
                'icon' => 'home',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 1,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'dashboard/analytics',
                'name' => 'Analytics',
                'icon' => 'circle',
                'slug' => 'dashboard-analytics',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 1,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => '/',
                'name' => 'eCommerce',
                'icon' => 'circle',
                'slug' => 'dashboard-ecommerce',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => NULL,
                'icon' => NULL,
                'slug' => '',
                'navheader' => 'Apps & Pages',
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/email',
                'name' => 'Email',
                'icon' => 'mail',
                'slug' => 'app-email',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            5 => 
            array (
                'id' => 6,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/chat',
                'name' => 'Chat',
                'icon' => 'message-square',
                'slug' => 'app-chat',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            6 => 
            array (
                'id' => 7,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/todo',
                'name' => 'Todo',
                'icon' => 'check-square',
                'slug' => 'app-todo',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            7 => 
            array (
                'id' => 8,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/calendar',
                'name' => 'Calendar',
                'icon' => 'calendar',
                'slug' => 'app-calendar',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 6,
            ),
            8 => 
            array (
                'id' => 9,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/kanban',
                'name' => 'Kanban',
                'icon' => 'grid',
                'slug' => 'app-kanban',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 7,
            ),
            9 => 
            array (
                'id' => 10,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Invoice',
                'icon' => 'file-text',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 8,
            ),
            10 => 
            array (
                'id' => 11,
                'parent_id' => 10,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/invoice/list',
                'name' => 'List',
                'icon' => 'circle',
                'slug' => 'app-invoice-list',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'parent_id' => 10,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/invoice/preview',
                'name' => 'Preview',
                'icon' => 'circle',
                'slug' => 'app-invoice-preview',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            12 => 
            array (
                'id' => 13,
                'parent_id' => 10,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/invoice/edit',
                'name' => 'Edit',
                'icon' => 'circle',
                'slug' => 'app-invoice-edit',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            13 => 
            array (
                'id' => 14,
                'parent_id' => 10,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/invoice/add',
                'name' => 'Add',
                'icon' => 'circle',
                'slug' => 'app-invoice-add',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            14 => 
            array (
                'id' => 15,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/file-manager',
                'name' => 'File Manager',
                'icon' => 'save',
                'slug' => 'app-file-manager',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 9,
            ),
            15 => 
            array (
                'id' => 16,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Roles & Permission',
                'icon' => 'shield',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 10,
            ),
            16 => 
            array (
                'id' => 17,
                'parent_id' => 16,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/access-roles',
                'name' => 'Roles',
                'icon' => 'circle',
                'slug' => 'app-access-roles',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'parent_id' => 16,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/access-permission',
                'name' => 'Permission',
                'icon' => 'circle',
                'slug' => 'app-access-permission',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            18 => 
            array (
                'id' => 19,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'eCommerce',
                'icon' => 'shopping-cart',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 11,
            ),
            19 => 
            array (
                'id' => 20,
                'parent_id' => 19,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/ecommerce/shop',
                'name' => 'Shop',
                'icon' => 'circle',
                'slug' => 'app-ecommerce-shop',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'parent_id' => 19,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/ecommerce/details',
                'name' => 'Details',
                'icon' => 'circle',
                'slug' => 'app-ecommerce-details',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            21 => 
            array (
                'id' => 22,
                'parent_id' => 19,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/ecommerce/wishlist',
                'name' => 'Wishlist',
                'icon' => 'circle',
                'slug' => 'app-ecommerce-wishlist',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            22 => 
            array (
                'id' => 23,
                'parent_id' => 19,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/ecommerce/checkout',
                'name' => 'Checkout',
                'icon' => 'circle',
                'slug' => 'app-ecommerce-checkout',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            23 => 
            array (
                'id' => 24,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'User',
                'icon' => 'user',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 12,
            ),
            24 => 
            array (
                'id' => 25,
                'parent_id' => 24,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/user/list',
                'name' => 'List',
                'icon' => 'circle',
                'slug' => 'app-user-list',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'parent_id' => 24,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'View',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            26 => 
            array (
                'id' => 27,
                'parent_id' => 26,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'user/profile',
                'name' => 'Account',
                'icon' => NULL,
                'slug' => 'profile.show',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'parent_id' => 26,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/user/view/security',
                'name' => 'Security',
                'icon' => NULL,
                'slug' => 'app-user-view-security',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            28 => 
            array (
                'id' => 29,
                'parent_id' => 26,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/user/view/billing',
                'name' => 'Billings & Plans',
                'icon' => NULL,
                'slug' => 'app-user-view-billing',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            29 => 
            array (
                'id' => 30,
                'parent_id' => 26,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/user/view/notifications',
                'name' => 'Notifications',
                'icon' => NULL,
                'slug' => 'app-user-view-notifications',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            30 => 
            array (
                'id' => 31,
                'parent_id' => 26,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'app/user/view/connections',
                'name' => 'Connections',
                'icon' => NULL,
                'slug' => 'app-user-view-connections',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            31 => 
            array (
                'id' => 32,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Pages',
                'icon' => 'file-text',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 13,
            ),
            32 => 
            array (
                'id' => 33,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Account Settings',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'parent_id' => 33,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'user/profile',
                'name' => 'Account',
                'icon' => NULL,
                'slug' => 'page-account-settings-account',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'parent_id' => 33,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/account-settings-security',
                'name' => 'Security',
                'icon' => NULL,
                'slug' => 'page-account-settings-security',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            35 => 
            array (
                'id' => 36,
                'parent_id' => 33,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/account-settings-billing',
                'name' => 'Billings & Plans',
                'icon' => NULL,
                'slug' => 'page-account-settings-billing',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            36 => 
            array (
                'id' => 37,
                'parent_id' => 33,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/account-settings-notifications',
                'name' => 'Notifications',
                'icon' => NULL,
                'slug' => 'page-account-settings-notifications',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            37 => 
            array (
                'id' => 38,
                'parent_id' => 33,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/account-settings-connections',
                'name' => 'Connections',
                'icon' => NULL,
                'slug' => 'page-account-settings-connections',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            38 => 
            array (
                'id' => 39,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/profile',
                'name' => 'Profile',
                'icon' => 'circle',
                'slug' => 'page-profile',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            39 => 
            array (
                'id' => 40,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/faq',
                'name' => 'FAQ',
                'icon' => 'circle',
                'slug' => 'page-faq',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            40 => 
            array (
                'id' => 41,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/knowledge-base',
                'name' => 'Knowledge Base',
                'icon' => 'circle',
                'slug' => 'page-knowledge-base',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            41 => 
            array (
                'id' => 42,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/pricing',
                'name' => 'Pricing',
                'icon' => 'circle',
                'slug' => 'page-pricing',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            42 => 
            array (
                'id' => 43,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/license',
                'name' => 'License',
                'icon' => 'circle',
                'slug' => 'page-license',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 6,
            ),
            43 => 
            array (
                'id' => 44,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/api-key',
                'name' => 'API Key',
                'icon' => 'circle',
                'slug' => 'page-api-key',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 7,
            ),
            44 => 
            array (
                'id' => 45,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Blog',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 8,
            ),
            45 => 
            array (
                'id' => 46,
                'parent_id' => 45,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/blog/list',
                'name' => 'List',
                'icon' => NULL,
                'slug' => 'page-blog-list',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'parent_id' => 45,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/blog/detail',
                'name' => 'Detail',
                'icon' => NULL,
                'slug' => 'page-blog-detail',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            47 => 
            array (
                'id' => 48,
                'parent_id' => 45,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/blog/edit',
                'name' => 'Edit',
                'icon' => NULL,
                'slug' => 'page-blog-edit',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            48 => 
            array (
                'id' => 49,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Mail Template',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 9,
            ),
            49 => 
            array (
                'id' => 50,
                'parent_id' => 49,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.com/demo/vuexy-mail-template/mail-welcome.html',
                'name' => 'Welcome',
                'icon' => NULL,
                'slug' => 'mail-welcome',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            50 => 
            array (
                'id' => 51,
                'parent_id' => 49,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.com/demo/vuexy-mail-template/mail-reset-password.html',
                'name' => 'Reset Password',
                'icon' => NULL,
                'slug' => 'mail-forgot',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            51 => 
            array (
                'id' => 52,
                'parent_id' => 49,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.com/demo/vuexy-mail-template/mail-verify-email.html',
                'name' => 'Verify Email',
                'icon' => NULL,
                'slug' => 'mail-verify',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            52 => 
            array (
                'id' => 53,
                'parent_id' => 49,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.com/demo/vuexy-mail-template/mail-deactivate-account.html',
                'name' => 'Deactivate Account',
                'icon' => NULL,
                'slug' => 'mail-deactivate',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            53 => 
            array (
                'id' => 54,
                'parent_id' => 49,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.com/demo/vuexy-mail-template/mail-invoice.html',
                'name' => 'Invoice',
                'icon' => NULL,
                'slug' => 'mail-invoice',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            54 => 
            array (
                'id' => 55,
                'parent_id' => 49,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.com/demo/vuexy-mail-template/mail-promotional.html',
                'name' => 'Promotional',
                'icon' => NULL,
                'slug' => 'mail-promotional',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 6,
            ),
            55 => 
            array (
                'id' => 56,
                'parent_id' => 32,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Miscellaneous',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 10,
            ),
            56 => 
            array (
                'id' => 57,
                'parent_id' => 56,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/coming-soon',
                'name' => 'Coming Soon',
                'icon' => NULL,
                'slug' => 'misc-analytics',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'parent_id' => 56,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/not-authorized',
                'name' => 'Not Authorized',
                'icon' => NULL,
                'slug' => 'misc-analytics',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            58 => 
            array (
                'id' => 59,
                'parent_id' => 56,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page/maintenance',
                'name' => 'Maintenance',
                'icon' => NULL,
                'slug' => 'misc-analytics',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            59 => 
            array (
                'id' => 60,
                'parent_id' => 56,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'error',
                'name' => 'Error',
                'icon' => NULL,
                'slug' => 'error',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            60 => 
            array (
                'id' => 61,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Authentication',
                'icon' => 'user-check',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 14,
            ),
            61 => 
            array (
                'id' => 62,
                'parent_id' => 61,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Login',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'parent_id' => 62,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/login-basic',
                'name' => 'Basic',
                'icon' => NULL,
                'slug' => 'auth-login-basic',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'parent_id' => 62,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/login-cover',
                'name' => 'Cover',
                'icon' => NULL,
                'slug' => 'auth-login-cover',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            64 => 
            array (
                'id' => 65,
                'parent_id' => 61,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Register',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            65 => 
            array (
                'id' => 66,
                'parent_id' => 65,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/register-basic',
                'name' => 'Basic',
                'icon' => NULL,
                'slug' => 'auth-register-basic',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            66 => 
            array (
                'id' => 67,
                'parent_id' => 65,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/register-cover',
                'name' => 'Cover',
                'icon' => NULL,
                'slug' => 'auth-register-cover',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            67 => 
            array (
                'id' => 68,
                'parent_id' => 65,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/register-multisteps',
                'name' => 'Multi-Steps',
                'icon' => NULL,
                'slug' => 'auth-register-multisteps',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            68 => 
            array (
                'id' => 69,
                'parent_id' => 61,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Forgot Password',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            69 => 
            array (
                'id' => 70,
                'parent_id' => 69,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/forgot-password-basic',
                'name' => 'Basic',
                'icon' => NULL,
                'slug' => 'auth-forgot-password-basic',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'parent_id' => 69,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/forgot-password-cover',
                'name' => 'Cover',
                'icon' => NULL,
                'slug' => 'auth-forgot-password-cover',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            71 => 
            array (
                'id' => 72,
                'parent_id' => 61,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Reset Password',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            72 => 
            array (
                'id' => 73,
                'parent_id' => 72,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/reset-password-basic',
                'name' => 'Basic',
                'icon' => NULL,
                'slug' => 'auth-reset-password-basic',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            73 => 
            array (
                'id' => 74,
                'parent_id' => 72,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/reset-password-cover',
                'name' => 'Cover',
                'icon' => NULL,
                'slug' => 'auth-reset-password-cover',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            74 => 
            array (
                'id' => 75,
                'parent_id' => 61,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Verify Email',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            75 => 
            array (
                'id' => 76,
                'parent_id' => 75,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/verify-email-basic',
                'name' => 'Basic',
                'icon' => NULL,
                'slug' => 'auth-verify-email-basic',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            76 => 
            array (
                'id' => 77,
                'parent_id' => 75,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/verify-email-cover',
                'name' => 'Cover',
                'icon' => NULL,
                'slug' => 'auth-verify-email-cover',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            77 => 
            array (
                'id' => 78,
                'parent_id' => 61,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Two Steps',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 6,
            ),
            78 => 
            array (
                'id' => 79,
                'parent_id' => 78,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/two-steps-basic',
                'name' => 'Basic',
                'icon' => NULL,
                'slug' => 'auth-two-steps-basic',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            79 => 
            array (
                'id' => 80,
                'parent_id' => 78,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'auth/two-steps-cover',
                'name' => 'Cover',
                'icon' => NULL,
                'slug' => 'auth-two-steps-cover',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            80 => 
            array (
                'id' => 81,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => '/modal-examples',
                'name' => 'Modal Examples',
                'icon' => 'square',
                'slug' => 'modal-examples',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 15,
            ),
            81 => 
            array (
                'id' => 82,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => NULL,
                'icon' => NULL,
                'slug' => '',
                'navheader' => 'User Interface',
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 16,
            ),
            82 => 
            array (
                'id' => 83,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ui/typography',
                'name' => 'Typography',
                'icon' => 'type',
                'slug' => 'ui-typography',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 17,
            ),
            83 => 
            array (
                'id' => 84,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'icons/feather',
                'name' => 'Feather',
                'icon' => 'eye',
                'slug' => 'icons-feather',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 18,
            ),
            84 => 
            array (
                'id' => 85,
                'parent_id' => NULL,
                'badge' => 'New',
                'badgeClass' => 'badge badge-light-success rounded-pill ms-auto me-1',
                'url' => NULL,
                'name' => 'Card',
                'icon' => 'credit-card',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 19,
            ),
            85 => 
            array (
                'id' => 86,
                'parent_id' => 85,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'card/basic',
                'name' => 'Basic',
                'icon' => 'circle',
                'slug' => 'card-basic',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            86 => 
            array (
                'id' => 87,
                'parent_id' => 85,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'card/advance',
                'name' => 'Advance',
                'icon' => 'circle',
                'slug' => 'card-advance',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            87 => 
            array (
                'id' => 88,
                'parent_id' => 85,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'card/statistics',
                'name' => 'Statistics',
                'icon' => 'circle',
                'slug' => 'card-statistics',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            88 => 
            array (
                'id' => 89,
                'parent_id' => 85,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'card/analytics',
                'name' => 'Analytics',
                'icon' => 'circle',
                'slug' => 'card-analytics',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            89 => 
            array (
                'id' => 90,
                'parent_id' => 85,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'card/actions',
                'name' => 'Card Actions',
                'icon' => 'circle',
                'slug' => 'card-actions',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            90 => 
            array (
                'id' => 91,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Components',
                'icon' => 'briefcase',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 20,
            ),
            91 => 
            array (
                'id' => 92,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/accordion',
                'name' => 'Accordion',
                'icon' => 'circle',
                'slug' => 'component-accordion',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            92 => 
            array (
                'id' => 93,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/alert',
                'name' => 'Alerts',
                'icon' => 'circle',
                'slug' => 'component-alert',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            93 => 
            array (
                'id' => 94,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/avatar',
                'name' => 'Avatar',
                'icon' => 'circle',
                'slug' => 'component-avatar',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            94 => 
            array (
                'id' => 95,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/badges',
                'name' => 'Badges',
                'icon' => 'circle',
                'slug' => 'component-badges',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            95 => 
            array (
                'id' => 96,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/breadcrumbs',
                'name' => 'Breadcrumbs',
                'icon' => 'circle',
                'slug' => 'component-breadcrumbs',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            96 => 
            array (
                'id' => 97,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/buttons',
                'name' => 'Buttons',
                'icon' => 'circle',
                'slug' => 'component-buttons',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 6,
            ),
            97 => 
            array (
                'id' => 98,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/carousel',
                'name' => 'Carousel',
                'icon' => 'circle',
                'slug' => 'component-carousel',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 7,
            ),
            98 => 
            array (
                'id' => 99,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/collapse',
                'name' => 'Collapse',
                'icon' => 'circle',
                'slug' => 'component-collapse',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 8,
            ),
            99 => 
            array (
                'id' => 100,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/divider',
                'name' => 'Divider',
                'icon' => 'circle',
                'slug' => 'component-divider',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 9,
            ),
            100 => 
            array (
                'id' => 101,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/dropdowns',
                'name' => 'Dropdowns',
                'icon' => 'circle',
                'slug' => 'component-dropdowns',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 10,
            ),
            101 => 
            array (
                'id' => 102,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/list-group',
                'name' => 'List Group',
                'icon' => 'circle',
                'slug' => 'component-list-group',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 11,
            ),
            102 => 
            array (
                'id' => 103,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/modals',
                'name' => 'Modals',
                'icon' => 'circle',
                'slug' => 'component-modals',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 12,
            ),
            103 => 
            array (
                'id' => 104,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/navs',
                'name' => 'Navs Component',
                'icon' => 'circle',
                'slug' => 'component-navs',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 13,
            ),
            104 => 
            array (
                'id' => 105,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/offcanvas',
                'name' => 'Offcanvas',
                'icon' => 'circle',
                'slug' => 'component-offcanvas',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 14,
            ),
            105 => 
            array (
                'id' => 106,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/pagination',
                'name' => 'Pagination',
                'icon' => 'circle',
                'slug' => 'component-pagination',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 15,
            ),
            106 => 
            array (
                'id' => 107,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/pill-badges',
                'name' => 'Pill Badges',
                'icon' => 'circle',
                'slug' => 'component-pill-badges',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 16,
            ),
            107 => 
            array (
                'id' => 108,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/pills',
                'name' => 'Pills Component',
                'icon' => 'circle',
                'slug' => 'component-pills',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 17,
            ),
            108 => 
            array (
                'id' => 109,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/popovers',
                'name' => 'Popovers',
                'icon' => 'circle',
                'slug' => 'component-popovers',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 18,
            ),
            109 => 
            array (
                'id' => 110,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/progress',
                'name' => 'Progress',
                'icon' => 'circle',
                'slug' => 'component-progress',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 19,
            ),
            110 => 
            array (
                'id' => 111,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/spinner',
                'name' => 'Spinner',
                'icon' => 'circle',
                'slug' => 'component-spinner',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 20,
            ),
            111 => 
            array (
                'id' => 112,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/tabs',
                'name' => 'Tabs Component',
                'icon' => 'circle',
                'slug' => 'component-tabs',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 21,
            ),
            112 => 
            array (
                'id' => 113,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/timeline',
                'name' => 'Timeline',
                'icon' => 'circle',
                'slug' => 'component-timeline',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 22,
            ),
            113 => 
            array (
                'id' => 114,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/toast',
                'name' => 'Toasts',
                'icon' => 'circle',
                'slug' => 'component-bs-toast',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 23,
            ),
            114 => 
            array (
                'id' => 115,
                'parent_id' => 91,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'component/tooltips',
                'name' => 'Tooltips',
                'icon' => 'circle',
                'slug' => 'component-tooltips',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 24,
            ),
            115 => 
            array (
                'id' => 116,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Extensions',
                'icon' => 'box',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 21,
            ),
            116 => 
            array (
                'id' => 117,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/sweet-alerts',
                'name' => 'Sweet Alert',
                'icon' => 'circle',
                'slug' => 'ext-component-sweet-alerts',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            117 => 
            array (
                'id' => 118,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/block-ui',
                'name' => 'BlockUI',
                'icon' => 'circle',
                'slug' => 'ext-component-block-ui',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            118 => 
            array (
                'id' => 119,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/toastr',
                'name' => 'Toastr',
                'icon' => 'circle',
                'slug' => 'ext-component-toastr',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            119 => 
            array (
                'id' => 120,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/sliders',
                'name' => 'Sliders',
                'icon' => 'circle',
                'slug' => 'ext-component-sliders',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            120 => 
            array (
                'id' => 121,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/drag-drop',
                'name' => 'Drag & Drop',
                'icon' => 'circle',
                'slug' => 'ext-component-drag-drop',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            121 => 
            array (
                'id' => 122,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/tour',
                'name' => 'Tour',
                'icon' => 'circle',
                'slug' => 'ext-component-tour',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 6,
            ),
            122 => 
            array (
                'id' => 123,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/clipboard',
                'name' => 'Clipboard',
                'icon' => 'circle',
                'slug' => 'ext-component-clipboard',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 7,
            ),
            123 => 
            array (
                'id' => 124,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/plyr',
                'name' => 'Media Player',
                'icon' => 'circle',
                'slug' => 'ext-component-plyr',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 8,
            ),
            124 => 
            array (
                'id' => 125,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/context-menu',
                'name' => 'Context Menu',
                'icon' => 'circle',
                'slug' => 'ext-component-context-menu',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 9,
            ),
            125 => 
            array (
                'id' => 126,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/swiper',
                'name' => 'Swiper',
                'icon' => 'circle',
                'slug' => 'ext-component-swiper',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 10,
            ),
            126 => 
            array (
                'id' => 127,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/tree',
                'name' => 'Tree',
                'icon' => 'circle',
                'slug' => 'ext-component-tree',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 11,
            ),
            127 => 
            array (
                'id' => 128,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/ratings',
                'name' => 'Ratings',
                'icon' => 'circle',
                'slug' => 'ext-component-ratings',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 12,
            ),
            128 => 
            array (
                'id' => 129,
                'parent_id' => 116,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'ext-component/locale',
                'name' => 'Locale',
                'icon' => 'circle',
                'slug' => 'ext-component-locale',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 13,
            ),
            129 => 
            array (
                'id' => 130,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Page Layouts',
                'icon' => 'layout',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 22,
            ),
            130 => 
            array (
                'id' => 131,
                'parent_id' => 130,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page-layouts/collapsed-menu',
                'name' => 'Collapsed Menu',
                'icon' => 'circle',
                'slug' => 'layout-collapsed-menu',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            131 => 
            array (
                'id' => 132,
                'parent_id' => 130,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page-layouts/full',
                'name' => 'Layout Full',
                'icon' => 'circle',
                'slug' => 'layout-full',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            132 => 
            array (
                'id' => 133,
                'parent_id' => 130,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page-layouts/without-menu',
                'name' => 'Without Menu',
                'icon' => 'circle',
                'slug' => 'layout-without-menu',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            133 => 
            array (
                'id' => 134,
                'parent_id' => 130,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page-layouts/empty',
                'name' => 'Layout Empty',
                'icon' => 'circle',
                'slug' => 'layout-empty',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            134 => 
            array (
                'id' => 135,
                'parent_id' => 130,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'page-layouts/blank',
                'name' => 'Layout Blank',
                'icon' => 'circle',
                'slug' => 'layout-blank',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            135 => 
            array (
                'id' => 136,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => NULL,
                'icon' => NULL,
                'slug' => '',
                'navheader' => 'Forms & Tables',
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 23,
            ),
            136 => 
            array (
                'id' => 137,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Form Elements',
                'icon' => 'copy',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 24,
            ),
            137 => 
            array (
                'id' => 138,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/input',
                'name' => 'Input',
                'icon' => 'circle',
                'slug' => 'form-input',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            138 => 
            array (
                'id' => 139,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/input-groups',
                'name' => 'Input Groups',
                'icon' => 'circle',
                'slug' => 'form-input-groups',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            139 => 
            array (
                'id' => 140,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/input-mask',
                'name' => 'Input Mask',
                'icon' => 'circle',
                'slug' => 'form-input-mask',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 3,
            ),
            140 => 
            array (
                'id' => 141,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/textarea',
                'name' => 'Textarea',
                'icon' => 'circle',
                'slug' => 'form-textarea',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 4,
            ),
            141 => 
            array (
                'id' => 142,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/checkbox',
                'name' => 'Checkbox',
                'icon' => 'circle',
                'slug' => 'form-checkbox',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 5,
            ),
            142 => 
            array (
                'id' => 143,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/radio',
                'name' => 'Radio',
                'icon' => 'circle',
                'slug' => 'form-radio',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 6,
            ),
            143 => 
            array (
                'id' => 144,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/custom-options',
                'name' => 'Custom Options',
                'icon' => 'circle',
                'slug' => 'form-custom-options',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 7,
            ),
            144 => 
            array (
                'id' => 145,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/switch',
                'name' => 'Switch',
                'icon' => 'circle',
                'slug' => 'form-switch',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 8,
            ),
            145 => 
            array (
                'id' => 146,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/select',
                'name' => 'Select',
                'icon' => 'circle',
                'slug' => 'form-select',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 9,
            ),
            146 => 
            array (
                'id' => 147,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/number-input',
                'name' => 'Number Input',
                'icon' => 'circle',
                'slug' => 'form-number-input',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 10,
            ),
            147 => 
            array (
                'id' => 148,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/file-uploader',
                'name' => 'File Uploader',
                'icon' => 'circle',
                'slug' => 'form-file-uploader',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 11,
            ),
            148 => 
            array (
                'id' => 149,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/quill-editor',
                'name' => 'Quill Editor',
                'icon' => 'circle',
                'slug' => 'form-quill-editor',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 12,
            ),
            149 => 
            array (
                'id' => 150,
                'parent_id' => 137,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/date-time-picker',
                'name' => 'Date & Time Picker',
                'icon' => 'circle',
                'slug' => 'form-date-time-picker',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 13,
            ),
            150 => 
            array (
                'id' => 151,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/layout',
                'name' => 'Form Layout',
                'icon' => 'box',
                'slug' => 'form-layout',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 25,
            ),
            151 => 
            array (
                'id' => 152,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/wizard',
                'name' => 'Form Wizard',
                'icon' => 'package',
                'slug' => 'form-wizard',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 26,
            ),
            152 => 
            array (
                'id' => 153,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/validation',
                'name' => 'Form Validation',
                'icon' => 'check-circle',
                'slug' => 'form-validation',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 27,
            ),
            153 => 
            array (
                'id' => 154,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'form/repeater',
                'name' => 'Form Repeater',
                'icon' => 'rotate-cw',
                'slug' => 'form-repeater',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 28,
            ),
            154 => 
            array (
                'id' => 155,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'table',
                'name' => 'Table',
                'icon' => 'server',
                'slug' => 'table',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 29,
            ),
            155 => 
            array (
                'id' => 156,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Datatable',
                'icon' => 'grid',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 30,
            ),
            156 => 
            array (
                'id' => 157,
                'parent_id' => 156,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'table/datatable/basic',
                'name' => 'Basic',
                'icon' => 'circle',
                'slug' => 'datatable-basic',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            157 => 
            array (
                'id' => 158,
                'parent_id' => 156,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'table/datatable/advance',
                'name' => 'Advanced',
                'icon' => 'circle',
                'slug' => 'datatable-advance',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            158 => 
            array (
                'id' => 159,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => NULL,
                'icon' => NULL,
                'slug' => '',
                'navheader' => 'Charts & Maps',
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 31,
            ),
            159 => 
            array (
                'id' => 160,
                'parent_id' => NULL,
                'badge' => '2',
                'badgeClass' => 'badge rounded-pill badge-light-danger ms-auto me-1',
                'url' => NULL,
                'name' => 'Charts',
                'icon' => 'pie-chart',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 32,
            ),
            160 => 
            array (
                'id' => 161,
                'parent_id' => 160,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'chart/apex',
                'name' => 'Apex',
                'icon' => 'circle',
                'slug' => 'chart-apex',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            161 => 
            array (
                'id' => 162,
                'parent_id' => 160,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'chart/chartjs',
                'name' => 'Chartjs',
                'icon' => 'circle',
                'slug' => 'chart-chartjs',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            162 => 
            array (
                'id' => 163,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'maps/leaflet',
                'name' => 'Leaflet Maps',
                'icon' => 'map',
                'slug' => 'map-leaflet',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 33,
            ),
            163 => 
            array (
                'id' => 164,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => NULL,
                'icon' => NULL,
                'slug' => '',
                'navheader' => 'Misc',
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 34,
            ),
            164 => 
            array (
                'id' => 165,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Menu Levels',
                'icon' => 'menu',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 35,
            ),
            165 => 
            array (
                'id' => 166,
                'parent_id' => 165,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Second Level 2.1',
                'icon' => 'circle',
                'slug' => 'menu-level',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            166 => 
            array (
                'id' => 167,
                'parent_id' => 165,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Second Level 2.2',
                'icon' => 'circle',
                'slug' => '',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            167 => 
            array (
                'id' => 168,
                'parent_id' => 167,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Third Level 3.1',
                'icon' => NULL,
                'slug' => 'menu-level',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 1,
            ),
            168 => 
            array (
                'id' => 169,
                'parent_id' => 167,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Third Level 3.2',
                'icon' => NULL,
                'slug' => 'menu-level',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 2,
            ),
            169 => 
            array (
                'id' => 170,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => NULL,
                'name' => 'Disabled Menu',
                'icon' => 'eye-off',
                'slug' => 'menu-disabled',
                'navheader' => NULL,
                'newTab' => NULL,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 36,
            ),
            170 => 
            array (
                'id' => 171,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.com/demo/vuexy-html-bootstrap-admin-template/documentation/documentation-laravel-folder-structure.html',
                'name' => 'Documentation',
                'icon' => 'folder',
                'slug' => 'documentation',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 37,
            ),
            171 => 
            array (
                'id' => 172,
                'parent_id' => NULL,
                'badge' => NULL,
                'badgeClass' => NULL,
                'url' => 'https://pixinvent.ticksy.com/',
                'name' => 'Raise Support',
                'icon' => 'life-buoy',
                'slug' => 'raise-support',
                'navheader' => NULL,
                'newTab' => 1,
                'created_at' => '2023-02-26 14:42:39',
                'updated_at' => '2023-02-26 14:42:39',
                'sequence' => 38,
            ),
        ));
        
        
    }
}